require "user.plugins"
require "user.lsp"
require "user.options"
require "user.keymaps"
require "user.colorscheme"

-- Plugins Settings --
require "user.pluginSettings.cmp"
require "user.pluginSettings.telescope"
require "user.pluginSettings.treesitter"
require "user.pluginSettings.autopairs"
require "user.pluginSettings.comment"
require "user.pluginSettings.nvim-tree"
require "user.pluginSettings.bufferline"
require "user.pluginSettings.toggleterm"
require "user.pluginSettings.lualine"
require "user.pluginSettings.gitsigns"
require "user.pluginSettings.project"
require "user.pluginSettings.impatient"
require "user.pluginSettings.indentline"
require "user.pluginSettings.alpha"
require "user.pluginSettings.whichkey"
-- require "user.pluginSettings.autocommands"
require "user.pluginSettings.astroConfig"
